### ISSUE TITLE
no detection in app, but very accurate using jupyter notebook

### ISSUE THREAD

**Issue by lhammond** [datitran/raccoon_dataset#25] opened 2017-10-03 20:09 UTC
Hi,
I've been able to train a dataset and have good accuracy using the object_detection_app_tutorial jupyter notebook with images from various sources.

however, when I do the following, I get no detection 

1. cp frozen_inference_graph.pb into object_detection/ssd_mobilenet_v1_coco_11_06_2017
2. cp label_map.pbtxt into data directory .. only a single entry
3. edit object_detection_app.py to change path to my label_map.pbtxt
4. edit object_detection_app.py and change NUM_CLASSES = 1
5. run the app

below is my training output .. any recommendations?

![image](https://user-images.githubusercontent.com/229602/31146442-bf3ae832-a854-11e7-9475-d8bc8c907ea0.png)

**Comment by datitran** [comment] 2017-10-04 20:15
Okay the problem is solved as I mistakenly used BGR instead of RGB. Fixed the code. Close the issue for now.

**Closed by datitran** 2017-10-04 20:15 UTC
